### ISSUE TITLE
Play selected starts at the wrong place when you are far into the composition (past 2000 pixels)

### ISSUE THREAD

**Issue by afelley** [WhitmanSWDesignSpring2018/project-5-8-teamalpha#122]
math issue? apparently the playline and the midiplayer are still in sync, it just starts too early

**Comment by ProfJanetDavis** [comment]
I also saw this:

<pre>
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: The time is invalid.
	at javafx.animation.KeyFrame.<init>(KeyFrame.java:189)
	at javafx.animation.KeyFrame.<init>(KeyFrame.java:226)
	at tunecomposer.PlayLine.play(PlayLine.java:79)
	at tunecomposer.TuneComposer.playSelected(TuneComposer.java:504)
</pre>
